BOOKING_STATUS_BOOKED = 'booked'
BOOKING_STATUS_CANCELLED = 'cancelled'
BOOKING_STATUS_ATTENDED = 'attended'
BOOKING_STATUS_NO_SHOW = 'no_show'
ALLOWED_BOOKING_STATUSES = [
    BOOKING_STATUS_BOOKED,
    BOOKING_STATUS_CANCELLED,
    BOOKING_STATUS_ATTENDED,
    BOOKING_STATUS_NO_SHOW
]